language: objective-c
osx_image: xcode12.2
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
install:
  - bundle install
script:
  - bundle exec fastlane build_framework source_code_url:https://$GITHUB_TOKEN@$SOURCE_CODE_URL
notifications:
  webhooks:
    secure: "KajTrasjO3d7+nckmrqOD8d3h5ccCTvFA8lqnU3yLVALxdDgLmvPBLfAjf78mvDnJn9mMacm2KikuTWruLqKl0VqLrBdcdihvwC5wDTdwCgZEriMAehv4AwPxmckSuvedxW9iH1WyZ1ZUzYwXfu5oDRO/JpZq6iQbs5pZfxjPUKRZstVwnaMZpPwMh9UH6rhpaWwdgwpEFdvP62bdcZvfKC3gsuKdKJ5MGlugZg9d1NXO1gmfGx8LcDM4PrdBXCkZqikAxBZ2fil3kvi5Nm2poOwPmms3eJgc4bsssrm4Zfm6lAEz2jO8Joh4FgLA1uhYXUGSrFc2lM8GYCCGL2agF46Gjja4N2KO769dUOf02iRWSGNUKpxyhAQ6vhvmVU6/oq6Gy9T4oN8oByVI8vUPh0RN3WQcxCzuU66342kMOKoEii5E43Ryau6Twjofcf4uAr1m21xd8FH9PjpN2HMFHuk3mAR18iNAQxXEZJ868lxYCErbVeHRiZMdaQI41rFTthhcSyZmOWhMaIFU4XZdODEHUPBdeqq3fYT/pSZZnZZebOu60SwTj3/nA4Z3XzdB5BiscOFiVdjp6AeB+wW0X1dZEYUxGuBTvZ3auTGCPpycsHrB9w/lgQYM6U7MMpnzr30Pmij9jDdTu4L8Drk+6Ej+hrm+f7K8fKsxTyw9jY="
